version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mercury-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mercury
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mercury-network

  db:
    image: postgres:latest
    container_name: mercury-postgres-db
    environment:
      - POSTGRES_DB=mercury
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mercuryuser -d mercurydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mercury-network

volumes:
  postgres-data:

networks:
  mercury-network:
    driver: bridge
